### ISSUE TITLE
it is lovely

### ISSUE THREAD

**Issue by Code-Victor** [Dev-Motion/paige#84]
# Description:
the wallpaper

﻿# Effect on UX:
too bright

﻿# Status:
This Feedback is Currently  of High Urgency.

 # Attachment
<img  src="https://resources.usersnap.com/company/e9558af2-2e8d-4ffa-81f0-049ef3464efe/datapoint_screenshot/e37c2033-9cca-45a9-8bfa-04ab7849a485-annotated_360db61e-b2c9-4c23-abb2-0b864c92ec9c.png?etag=d7b99d20be535cd10a3c32a1fdad5193"  alt="user issue"/>

**Comment by OVECJOE** [comment]
The image in the **Attachment** section is broken.

**Comment by Code-Victor** [comment]
Sorry, this isn't a real issue. 
I was testing an automation flow to open an issue for every user feed. I'll mark this as closed.
